# Generated by Django 3.2.9 on 2021-11-21 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=False)),
                ('soon', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=128)),
                ('title_uk', models.CharField(max_length=128, null=True)),
                ('title_ru', models.CharField(max_length=128, null=True)),
                ('image', models.FileField(upload_to='images/')),
                ('short_description', models.TextField()),
                ('short_description_uk', models.TextField(null=True)),
                ('short_description_ru', models.TextField(null=True)),
                ('description', models.TextField()),
                ('description_uk', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payed', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acan.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=128)),
                ('title_uk', models.CharField(max_length=128, null=True)),
                ('title_ru', models.CharField(max_length=128, null=True)),
                ('description', models.TextField()),
                ('description_uk', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('video', models.FileField(upload_to='')),
                ('addon', models.FileField(blank=True, null=True, upload_to='addons/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acan.course')),
            ],
        ),
    ]
