# Generated by Django 3.2.9 on 2021-12-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acan', '0002_auto_20211206_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mailing_list',
            field=models.BooleanField(default=False),
        ),
    ]
