# Generated by Django 3.2.9 on 2021-11-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acan', '0002_course_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
