# Generated by Django 3.2.12 on 2022-03-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acan', '0003_user_mailing_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=128)),
                ('title_uk', models.CharField(max_length=128, null=True)),
                ('title_ru', models.CharField(max_length=128, null=True)),
                ('image', models.FileField(upload_to='article_images/')),
                ('text', models.TextField()),
                ('text_uk', models.TextField(null=True)),
                ('text_ru', models.TextField(null=True)),
            ],
        ),
    ]
