# Generated by Django 3.2.9 on 2021-11-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acan', '0004_alter_lesson_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='addon',
            field=models.FileField(blank=True, null=True, upload_to='addons/'),
        ),
    ]
