# Generated by Django 3.2.12 on 2022-03-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acan', '0004_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='order_int',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
