# Generated by Django 3.2.9 on 2021-11-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acan', '0005_alter_lesson_addon'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.FileField(default='kek', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='soon',
            field=models.BooleanField(default=False),
        ),
    ]
