# Generated by Django 3.2.13 on 2022-07-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acan', '0007_alter_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='discount_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='discount_deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
