# Generated by Django 3.2.25 on 2024-08-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acan', '0008_auto_20220724_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description_uk',
            field=models.TextField(blank=True, null=True),
        ),
    ]
