# Generated by Django 3.2.25 on 2024-08-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acan', '0010_alter_lesson_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
